// This file is automatically generated by Flutter.
// Do not edit this file directly.
// See https://github.com/flutter/flutter/wiki/Web-APIs for more information.

(function() {
  'use strict';
  
  // Flutter web entry point
  var serviceWorkerVersion = null;
  
  // Initialize Flutter web
  if (typeof window !== 'undefined') {
    window.flutterConfiguration = {
      canvasKitBaseUrl: "/canvaskit/"
    };
  }
  
  // Export for WASM compatibility
  if (typeof module !== 'undefined' && module.exports) {
    module.exports = {
      serviceWorkerVersion: serviceWorkerVersion
    };
  }
})();
